### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by teolnvl** [JH-Soft-Technology/InelsForHass#2] opened 2021-03-26 16:01 UTC
Hello. After installation does not load components from connection server.
server log:
Logger: custom_components.inels
Source: helpers/update_coordinator.py:173
Integration: Inels (documentation)
First occurred: 18:38:30 (8 occurrences)
Last logged: 18:43:45

Error fetching inels data: 'NoneType' object is not callable
Logger: homeassistant.util.async_
Source: util/async_.py:129
First occurred: 18:38:30 (24 occurrences)
Last logged: 18:43:45

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for inels doing I/O at custom_components/inels/__init__.py, line 91: data = self.api.getAllDevices()

Logger: homeassistant.config_entries
Source: config_entries.py:260
First occurred: 18:38:30 (1 occurrences)
Last logged: 18:38:30

Config entry 'Inels' for inels integration not ready yet. Retrying in background

**Comment by jhoralek** [comment] 2021-04-27 08:31
Hello,

there is a problem with NoneType object. So it means, you are using some kind of non supported device with integration. There is a couple of types. 

I'm going to add a feature, that will ignore not known devices. 

The thing with stability issue is known and does not have any negative effect on function.

I need to find a time to solve issue with "event loop" and add the feature, that will ignore not known devices.

**Comment by jhoralek** [comment] 2021-11-27 22:48
Only switches and lights are available at the moment. 
Closing this issue

**Closed as completed by jhoralek** 2021-11-27 22:48 UTC
Labels: bug

**Comment by domenix** [comment] 2021-12-22 02:13
Hi, did you by any chance add the feature that will ignore not known devices? I am setting up this integration for a home with a lots of Inels BUS devices, and I am getting this error and not seeing any inels devices in Node Red.
Do you accept contributions here and in your pyinels project?

**Comment by jhoralek** [comment] 2021-12-22 13:59
Hi Domenix,

no this repo and pyinels repo are only mirrors for devops.

What kind of not know devices you have? Integration works only with switches, lights, doors and shutters. 
Door is the same as switch. Difference is only that the door object has no state, because it is a pulse switch.

If you are familiar with python, you can use pyinels library to get raw text data of you devices from it. Then you can find what is not know, or you can post that text result here and I'll take look at it.

[pyInels API](https://github.com/JH-Soft-Technology/pyinels/blob/master/pyinels/api/__init__.py) getRoomDevicesRaw method will give you raw result of all device in specific room. First get all room names and then put them all as param into the getRoomDeviceRaw. Use loop for that purpose.

**Comment by domenix** [comment] 2021-12-23 03:35
Thanks for the reply @jhoralek!

I managed to find the issue. The different device types are chosen based on the matching key in [`DEVICE_TYPE_DICT`](https://github.com/JH-Soft-Technology/pyinels/blob/master/pyinels/const.py#L28) (on_off, heat-control, etc.). If it can't be resolved, then [`DEVICE_TYPE_DICT.get(d_type)`](https://github.com/JH-Soft-Technology/pyinels/blob/master/pyinels/api/__init__.py#L195) will resolve to `None`, which will later cause the `TypeError: 'NoneType' object is not callable` error inside [`__recognizeAndSetUniqueIdToDevice`](https://github.com/JH-Soft-Technology/pyinels/blob/master/pyinels/api/__init__.py#L236).

A quick solution to this problem that is less error-prone is to completely ignore devices that have unknown types (according to DEVICE_TYPE_DICT). I'd add the following comparison above [`pyinels/api/__init__.py#L195`](https://github.com/JH-Soft-Technology/pyinels/blob/master/pyinels/api/__init__.py#L195):

```python
if DEVICE_TYPE_DICT.get(d_type) is None:
    break
```

<br/>

Now the actual issue is that the `scenes` d_type is not supported in pyinels. I am not sure what the `scenes` group should represent, but it has Python script entries that run on the connection server and these can also be executed manually through the Inels mobile application.

As an example, if I try to print the `obj` below [`pyinels/api/__init__.py#L194`](https://github.com/JH-Soft-Technology/pyinels/blob/master/pyinels/api/__init__.py#L194) I get the following line:
`{'group': 'irrigation system', 'name': 'start irrigation immediately', 'column': '0', 'abs_path': '/etc/imm/scripts/irrigate_immediately.py', 'row': '5', 'type': None}`

In order to ignore `scenes` specifically, I'd add the following lines after [`pyinels/api/__init__.py#L184`](https://github.com/JH-Soft-Technology/pyinels/blob/master/pyinels/api/__init__.py#L184):

```python
if d_type in "scenes":
    break
```

This way only `scenes` devices are skipped for now, for any future group types, pyinels would fail at runtime again.

<br/>

After modifying the python script directly in the site-packages folder inside the Home Assistant docker container and restarting the InelsForHass integration that was loaded through HACS, the integration was able to find all (240+) Inels entities around the house and I will try soon if it is possible to automate these entities using Google Home voice commands. I'd like to thank you for your awesome work Jiří!

**Comment by jhoralek** [comment] 2021-12-23 07:53
Hi @domenix,

please contact me on my email. I will include you in the pyInels and InelsForHass projects in devops. I just need an email to send an invitation. Your consideration for modifying the pyInels library is correct.

**Comment by jhoralek** [comment] 2021-12-23 09:20
I went just through the issue and I'm wonder what kind of type it is from inels output string.

I do not have any scenes on IMM connection server, so I'm not able to get the row with row data of the scenes.

[`pyinels/api/__init__.py#L177`](https://github.com/JH-Soft-Technology/pyinels/blob/master/pyinels/api/__init__.py#L177) Is a array device_list

```python
devices_list = raw_list.split('\n')
```

which represents all device on each row. Some rows are types and underneath them are devices like lights, switches, etc. 

Example:
```text
on_off:
name="Zas OB" column="0" inels="ZAS_1A_Obyvak" read_only="no" row="2"
name="Zas POK" column="1" inels="ZAS_1B_Pokoj_dole" read_only="no" row="2"
name="Zas POK" column="1" inels="ZAS_1B_Pokoj_dole" read_only="no" row="2"
thermals:
name="Obyvak" inels="Koupelna_dole_StateTH" placement="indoor"
heating:
name="DOVOLENA" column="0" inels="DIGITALGROUP_0001" read_only="no" row="5"
lights:
name="Obyvak" column="0" inels="SV_1_Obyvak_strop" read_only="no" row="0"
name="Stul" column="1" inels="SV_2_Jidelni_stul" read_only="no" row="0"
```

I would appreciate it if you could send me this field here or by e-mail and I would write tests that would reveal to me what other devices I could add or possibly fix any issues.

**Comment by domenix** [comment] 2021-12-23 16:42
Without the modification pyinels throws an error in the very first room, which is "öntöző rendszer". This means irrigation system.
Here's the unaltered output of the `getRoomDevicesRaw` method, except some street names are replaced.

```
on_off:
name="öntöző rendszer be ki" column="0" inels="ontozes_be_ki" read_only="no" row="0"
name="öntözést tiltó bit" column="1" inels="szokokut_tilt_bit" read_only="yes" row="0"
name="szökőkút feltöltést tiltó bit" column="2" inels="ontozo_tilt_bit" read_only="yes" row="0"
name="esőérzékelő" column="3" inels="esoerzekelo" read_only="yes" row="0"
name="esőérzékelő szűrve" column="4" inels="esoerzekelo_bit" read_only="yes" row="0"
name="központi elzáró" column="5" inels="kozponti_elzaro" read_only="no" row="0"
name="gyep elől" column="6" inels="gyep_elol" read_only="no" row="0"
name="gyep oldalt" column="7" inels="gyep_oldalt" read_only="no" row="0"
name="hátsó kapu gyep" column="8" inels="hatso_kapu_gyep" read_only="no" row="0"
name="hátsó terasz gyep" column="9" inels="hatso_terasz" read_only="no" row="0"
name="Street A out 1" column="10" inels="Street_A_out_1" read_only="no" row="0"
name="Street A out 2" column="11" inels="Street_A_out_2" read_only="no" row="0"
name="konyhakert mellett" column="12" inels="konyhakert_mellett" read_only="no" row="0"        
name="konyhakert" column="13" inels="konyhakert" read_only="no" row="0"
name="tuja elöl csepegtető" column="14" inels="tuja_elol_csepp" read_only="no" row="0"
name="tuja oldalt csepegtető" column="15" inels="tuja_oldalt_csepp" read_only="no" row="0"     
name="hóember 1" column="16" inels="hoember_1" read_only="no" row="0"
name="magaságyás csepegtető" column="17" inels="magasagyas_csepp" read_only="no" row="0"       
name="Street B out 2" column="18" inels="Street_B_out_2" read_only="no" row="0"
name="szabadság öntöző" column="19" inels="szabadsag_ontozo" read_only="no" row="0"
name="szökőkút feltöltés" column="20" inels="szokokut_feltolt" read_only="no" row="0"
name="öntözési  gyakoriság +" column="0" inels="ont_gyak_plusz" read_only="no" row="2"
name="öntözési  gyakoriság -" column="1" inels="ont_gyak_minusz" read_only="no" row="2"
name="öntözési mennyiség +" column="0" inels="csapadek_plusz" read_only="no" row="4"
name="öntözési mennyiség -" column="1" inels="csapadek_minusz" read_only="no" row="4"
scenes:
name="öntözés azonnal" column="0" abs_path="/etc/imm/scripts/ontozes_azonnal.py" row="5"
name="keltető, frissítő öntözés" column="1" abs_path="/etc/imm/scripts/kelteto_ont.py" row="5"
meter:
name="öntözés óta eltelt nap" inels="ont_eltelt_nap_sz" min_disp="0" column="21" koef_mult="1.0" max_disp="7" decimal_digits="1" koef_add="0.0" units="nap" row="0"
name="öntözési gyakoriság" inels="ont_gyak_sz" min_disp="0" column="0" koef_mult="1.0" max_disp="7" decimal_digits="1" koef_add="0.0" units="naponta" row="1"
name="öntözési mennyiség" inels="ont_mennyiseg_sz" min_disp="0" column="0" koef_mult="1.0" max_disp="12" decimal_digits="1" koef_add="0.0" units="mm/m2" row="3"
blank:
name=" " column="1" inels="ejfel_bit" read_only="no" row="3"
```

The CU used is a CU3-02M using firmware 02.8C.00, hardware revision 01.04.00, and the connection server has the firmware version connection-server-3.366.
I also sent you an email regarding the invite.

**Comment by jhoralek** [comment] 2021-12-23 17:00
@domenix, thanks for raw data from your inels instalation. 

I already fixed that issue. Found better solution.

When not known device is found then will create device as unknow type. InelsForHass will ignore it. I hope. 

Made new package release 0.6.11 and upgrade InelsForHass integration.

I'll send you invitation into devops projects ASAP.

Will use your data to adopt not know type devices into the pyinels library.

I'm in touch with iNELS dev team, so maybe they will give some API documentation for scenes or meter.

Kind regards

**Comment by domenix** [comment] 2021-12-23 17:25
That sounds awesome, thanks!
I also discovered, that all light entities are missing from Home Assistant, and it turns out I receive `lamps` instead of `lights` from Inels. Is there a difference? If I map `lamps` to `light`, just like you map `lights` to `light` in `DEVICE_TYPE_DICT`, will there be any control implementation difference apart from different icons in the mobile app? I also receive thermals only, no heat-control devices are present, at all.

The IDM version is 3.3.27.22083, the owner of the home has not updated yet as it requires some rework of the heating system, so maybe that could be the cause, at least for the thermals vs heat-control part.

**Comment by domenix** [comment] 2021-12-23 17:28
See this image for reference.
![image](https://user-images.githubusercontent.com/4574333/147273902-176a3752-9bbb-4f7f-bf2c-a2f0895bb487.png)

Left one is light, right one is lamp. He uses lamps only in the house.

**Comment by jhoralek** [comment] 2021-12-23 17:37
There shouldn't be any difference between lights and lamps.

I've already seen the data you sent me in email, and there is no lights or lamps devices.

Did I miss somthing?

Please let's go and move this conversation to the email.

Thanks.
